In [1]:
# Import required Libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from pathlib import Path
from textblob import TextBlob

In [2]:
# Store filepaths to variables
Cancer_disease_prediction = Path("Data/Cancer Disease Prediction.csv")
patient_data = Path("Data/Colorectal Cancer Patient Data.csv")
supplementary_data = Path("Data/supplementary data- deidentified colorectal data.csv")

In [3]:
#Read in files
Cancer_disease_prediction_df = pd.read_csv(Cancer_disease_prediction)
patient_data_df = pd.read_csv(patient_data)
supplementary_data_df = pd.read_csv(supplementary_data)

In [4]:
# Display sample data
Cancer_disease_prediction_df.head()

,Unnamed: 0,patient_id,age,gender,smoking_status,alcohol_intake,physical_activity,family_history,medical_history,cancer_type,cancer_stage
0,0,4055,29,male,former,light,high,yes,Respiratory Diseases,Mouth,III
1,1,746,72,male,former,moderate,low,no,Respiratory Diseases,Brain,IV
2,2,1050,10,male,current,none,moderate,yes,Stroke,ovarian,II
3,3,4139,35,male,former,heavy,low,no,Stroke,Lymph,IV
4,4,119,6,female,former,none,moderate,no,Thyroid,lung,IV

In [5]:
# Display sample data
patient_data_df.head()

,Unnamed: 0,ID_REF,Age (in years),Dukes Stage,Gender,Location,DFS (in months),DFS event,Adj_Radio,Adj_Chem
0,0,GSM877126,62.0,A,Male,Left,108.0,0.0,1.0,0.0
1,1,GSM877127,77.0,B,Male,Left,40.0,1.0,1.0,0.0
2,2,GSM877128,66.0,C,Female,Left,49.0,0.0,1.0,0.0
3,3,GSM877129,72.0,D,Female,Left,45.0,0.0,1.0,1.0
4,4,GSM877130,75.0,C,Male,Left,40.0,0.0,0.0,1.0

In [6]:
# Display sample data
supplementary_data_df.head()

,Age at diagnosis,Sex,ethnicity,race,Cancer directed surgery type,Cancer directed surgery date,Diagnosed before age 50?,Histology,Histologic Grade,Neoadjuvant therapy?,...,T,N,M,MSI Instability Y or N,"If Yes MSI instability, high or low",perineural invasion (Y/N),Lymphovascular invasion (Y/N),TNM Staging,Metastases Type,Synchronous/Metachronous
0,70,Female,Non-spanish,White,"Partial colectomy, s/ LAR",12/03/20,N,"Adenocarcinoma, NOS;",G2,Y,...,3,0,0.0,N,NaN,N,N,IIA,NaN,NaN
1,67,Male,Non-spanish,White,"Partial colectomy, s/ LAR",03/18/20,N,"Adenocarcinoma, NOS;",G2,Y,...,3,0,1.0,N,NaN,N,N,IVA,Multiple CRLM,NaN
2,64,Female,Non-spanish,Black,Subtotal colectomy/h,03/02/20,N,"Adenocarcinoma, NOS;",G2,N,...,3,1,0.0,N,NaN,N,Y,IIIB,NaN,NaN
3,52,Male,Non-spanish,Black,Subtotal colectomy/h,02/17/20,N,"Adenocarcinoma, NOS;",G2,Y,...,3,1,0.0,N,NaN,N,Y,IIIB,NaN,NaN
4,53,Female,Non-spanish,Black,combination of 40 Pl,12/26/19,N,"Adenocarcinoma, NOS;",G2,N,...,3,0,1.0,Y,low,N,N,IVA,NaN,NaN

## CLEAN SUPPLEMENTARY DATA

In [7]:
# Filter supplementary_data_df 
cleaned_supplementary_df = supplementary_data_df[["Age at diagnosis", "Sex", "ethnicity", "race", "Cancer directed surgery type", 
                                                  "Diagnosed before age 50?", "Histology", "Histologic Grade", "Tumor size (cm)", 
                                                  "Nodes examined", "Nodes positive", "perineural invasion (Y/N)", 
                                                  "Lymphovascular invasion (Y/N)", "TNM Staging",]]
cleaned_supplementary_df.head()

,Age at diagnosis,Sex,ethnicity,race,Cancer directed surgery type,Diagnosed before age 50?,Histology,Histologic Grade,Tumor size (cm),Nodes examined,Nodes positive,perineural invasion (Y/N),Lymphovascular invasion (Y/N),TNM Staging
0,70,Female,Non-spanish,White,"Partial colectomy, s/ LAR",N,"Adenocarcinoma, NOS;",G2,2.0,14,0,N,N,IIA
1,67,Male,Non-spanish,White,"Partial colectomy, s/ LAR",N,"Adenocarcinoma, NOS;",G2,5.8,12,0,N,N,IVA
2,64,Female,Non-spanish,Black,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,10.5,9,0,N,Y,IIIB
3,52,Male,Non-spanish,Black,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,4.2,30,2,N,Y,IIIB
4,53,Female,Non-spanish,Black,combination of 40 Pl,N,"Adenocarcinoma, NOS;",G2,6.5,31,0,N,N,IVA

In [8]:
# Rename columns cleaned_supplementary_df
cleaned_supplementary_df = cleaned_supplementary_df.rename(columns={"Age at diagnosis":"Age_at_diagnosis", 
                                                                    "Sex":"Gender", "ethnicity": "Ethnicity", "race":"Race",
                                                                    "Cancer directed surgery type": "Surgery_type",
                                                                    "Diagnosed before age 50?": "Diagnosed_before_age_50", 
                                                                    "Histologic Grade":"Histologic_Grade", "Tumor size (cm)":"Tumor_Size_cm",
                                                                    "Nodes examined": "Nodes_examined",
                                                                    "Nodes positive": "Nodes_positive",
                                                                    "perineural invasion (Y/N)": "Perineural_invasion",
                                                                    "Lymphovascular invasion (Y/N)": "Lymphovascular_invasion",                                                                    
                                                                    "TNM Staging":"TNM_Staging",})
cleaned_supplementary_df =cleaned_supplementary_df.dropna()
cleaned_supplementary_df.head()

,Age_at_diagnosis,Gender,Ethnicity,Race,Surgery_type,Diagnosed_before_age_50,Histology,Histologic_Grade,Tumor_Size_cm,Nodes_examined,Nodes_positive,Perineural_invasion,Lymphovascular_invasion,TNM_Staging
0,70,Female,Non-spanish,White,"Partial colectomy, s/ LAR",N,"Adenocarcinoma, NOS;",G2,2.0,14,0,N,N,IIA
1,67,Male,Non-spanish,White,"Partial colectomy, s/ LAR",N,"Adenocarcinoma, NOS;",G2,5.8,12,0,N,N,IVA
2,64,Female,Non-spanish,Black,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,10.5,9,0,N,Y,IIIB
3,52,Male,Non-spanish,Black,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,4.2,30,2,N,Y,IIIB
4,53,Female,Non-spanish,Black,combination of 40 Pl,N,"Adenocarcinoma, NOS;",G2,6.5,31,0,N,N,IVA

In [9]:
cleaned_supplementary_df["TNM_Staging"].unique()

array(['IIA', 'IVA', 'IIIB', 'I', 'IVC', 'IIB', 'IIIA', 'IV?', 'IVB',
       'IIIC', 'IIa', 'IIC'], dtype=object)

In [10]:
# Map TNM Staging to Dukes Staging

# Convert values in 'TNM Staging' column to uppercase
cleaned_supplementary_df['TNM_Staging'] = cleaned_supplementary_df['TNM_Staging'].str.upper()

# Map TNM Staging to Dukes Staging
tnm_to_dukes_mapping = {
    'I': 'A',
    'IIA': 'B',
    'IIB': 'B',
    'IIC': 'B',
    'IIIA': 'C',
    'IIIB': 'C',
    'IIIC': 'C',
    'IV?': 'D',
    'IVA': 'D',
    'IVB': 'D',
    'IVC': 'D',
}
dukes_stage_list = [tnm_to_dukes_mapping[tnm] for tnm in cleaned_supplementary_df['TNM_Staging']]
cleaned_supplementary_df['Dukes_Stage'] = dukes_stage_list
cleaned_supplementary_df.head()

,Age_at_diagnosis,Gender,Ethnicity,Race,Surgery_type,Diagnosed_before_age_50,Histology,Histologic_Grade,Tumor_Size_cm,Nodes_examined,Nodes_positive,Perineural_invasion,Lymphovascular_invasion,TNM_Staging,Dukes_Stage
0,70,Female,Non-spanish,White,"Partial colectomy, s/ LAR",N,"Adenocarcinoma, NOS;",G2,2.0,14,0,N,N,IIA,B
1,67,Male,Non-spanish,White,"Partial colectomy, s/ LAR",N,"Adenocarcinoma, NOS;",G2,5.8,12,0,N,N,IVA,D
2,64,Female,Non-spanish,Black,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,10.5,9,0,N,Y,IIIB,C
3,52,Male,Non-spanish,Black,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,4.2,30,2,N,Y,IIIB,C
4,53,Female,Non-spanish,Black,combination of 40 Pl,N,"Adenocarcinoma, NOS;",G2,6.5,31,0,N,N,IVA,D

In [13]:
#save dataframe to a CSV file
cleaned_supplementary_df.to_csv('cleaned_supplementary.csv', index=False)

In [14]:
# Sample text
a = "Spanish, Nos; Hispan"           # incorrect spelling
print("original text: " + str(a))

# Replace the incorrect term with the correct word
a_corrected = a.replace("Spanish, Nos; Hispan", "Spanish")
print("corrected text: " + str(a_corrected))

original text: Spanish, Nos; Hispan
corrected text: Spanish

In [15]:
# Define a function to correct the spelling using TextBlob
def correct_spelling(text):
    return text.replace("Spanish, Nos; Hispan", "Spanish")

# Assuming cleaned_supplementary_df is your DataFrame
# Apply the correction function to the 'Ethnicity' column using apply() and lambda
cleaned_supplementary_df['Ethnicity'] = cleaned_supplementary_df['Ethnicity'].apply(lambda x: correct_spelling(x))

# Print the DataFrame with corrected text
cleaned_supplementary_df.head(20)

,Age_at_diagnosis,Gender,Ethnicity,Race,Surgery_type,Diagnosed_before_age_50,Histology,Histologic_Grade,Tumor_Size_cm,Nodes_examined,Nodes_positive,Perineural_invasion,Lymphovascular_invasion,TNM_Staging,Dukes_Stage
0,70,Female,Non-spanish,White,"Partial colectomy, s/ LAR",N,"Adenocarcinoma, NOS;",G2,2.0,14,0,N,N,IIA,B
1,67,Male,Non-spanish,White,"Partial colectomy, s/ LAR",N,"Adenocarcinoma, NOS;",G2,5.8,12,0,N,N,IVA,D
2,64,Female,Non-spanish,Black,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,10.5,9,0,N,Y,IIIB,C
3,52,Male,Non-spanish,Black,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,4.2,30,2,N,Y,IIIB,C
4,53,Female,Non-spanish,Black,combination of 40 Pl,N,"Adenocarcinoma, NOS;",G2,6.5,31,0,N,N,IVA,D
5,83,Male,Non-spanish,White,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,6.0,40,0,N,Y,I,A
6,84,Male,Non-spanish,White,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G3,6.0,32,0,Y,Y,IIA,B
7,78,Male,Non-spanish,White,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,0.7,24,0,N,N,I,A
8,53,Male,Non-spanish,White,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,2.5,19,0,N,N,I,A
9,49,Male,Non-spanish,White,Subtotal colectomy/h,Y,"Adenocarcinoma, NOS;",G2,5.5,2,2,Y,Y,IVC,D
10,42,Male,Non-spanish,White,Subtotal colectomy/h,Y,"Adenocarcinoma, NOS;",G2,12.0,30,1,N,N,IIIB,C
11,67,Male,Non-spanish,Black,Total colectomy (rem,N,"Adenocarcinoma, NOS;",G2,4.1,34,2,Y,Y,IIIB,C
12,91,Female,Non-spanish,White,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G3,5.0,13,1,N,Y,IIIB,C
13,71,Male,Non-spanish,Black,Colectomy or colopro,N,"Adenocarcinoma, NOS;",G2,3.7,13,2,Y,Y,IIIB,C
15,71,Female,Non-spanish,White,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,3.4,14,2,Y,Y,IIIB,C
16,59,Male,Non-spanish,White,Total proctocolectom,N,"Adenocarcinoma, NOS;",G2,6.2,79,0,N,Y,IIA,B
17,63,Male,Non-spanish,White,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G2,5.0,39,0,Y,Y,IIA,B
18,52,Male,Non-spanish,White,"Partial colectomy, s",N,"Adenocarcinoma, NOS;",G2,9.1,49,0,N,N,IIA,B
19,64,Male,Spanish,White,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G1,0.8,21,0,N,N,I,A
20,64,Female,Non-spanish,White,Subtotal colectomy/h,N,"Adenocarcinoma, NOS;",G3,3.5,13,6,N,Y,IIIB,C

In [16]:
#save dataframe to a CSV file
cleaned_supplementary_df.to_csv('cleaned_supplementary.csv', index=False)

## CLEAN PATIENT DATA

In [17]:
# Filter patient_data_df 
cleaned_patient_df = patient_data_df[["Age (in years)", "Gender", "DFS (in months)", "DFS event", "Adj_Radio", "Adj_Chem", "Dukes Stage"]]
cleaned_patient_df =cleaned_patient_df.dropna()

#convert Age into integers and Months into integers
cleaned_patient_df['Age (in years)'] = cleaned_patient_df['Age (in years)'].astype(int)
cleaned_patient_df['DFS (in months)'] = cleaned_patient_df['DFS (in months)'].astype(int)
cleaned_patient_df.head()

,Age (in years),Gender,DFS (in months),DFS event,Adj_Radio,Adj_Chem,Dukes Stage
0,62,Male,108,0.0,1.0,0.0,A
1,77,Male,40,1.0,1.0,0.0,B
2,66,Female,49,0.0,1.0,0.0,C
3,72,Female,45,0.0,1.0,1.0,D
4,75,Male,40,0.0,0.0,1.0,C

In [18]:
# Rename columns cleaned_patient_df
cleaned_patient_df = cleaned_patient_df.rename(columns={"Age (in years)":"Age_at_diagnosis",
                                                        "DFS (in months)":"DFS_in_months",
                                                        "DFS event": "DFS_event",
                                                        "Dukes Stage":"Dukes_Stage"})
cleaned_patient_df.head()

,Age_at_diagnosis,Gender,DFS_in_months,DFS_event,Adj_Radio,Adj_Chem,Dukes_Stage
0,62,Male,108,0.0,1.0,0.0,A
1,77,Male,40,1.0,1.0,0.0,B
2,66,Female,49,0.0,1.0,0.0,C
3,72,Female,45,0.0,1.0,1.0,D
4,75,Male,40,0.0,0.0,1.0,C

In [19]:
#save dataframe to a CSV file
cleaned_patient_df.to_csv('cleaned_patient.csv', index=False)

## CLEAN CANCER DISEASE

In [20]:
# Filter Cancer_disease_prediction_df
cleaned_cancer_disease_prediction_df = Cancer_disease_prediction_df[["age", "gender", "smoking_status", "alcohol_intake", 
                                                                     "physical_activity", "family_history", "medical_history",
                                                                     "cancer_type", "cancer_stage"]]
cleaned_cancer_disease_prediction_df = cleaned_cancer_disease_prediction_df.dropna()
cleaned_cancer_disease_prediction_df.head()

,age,gender,smoking_status,alcohol_intake,physical_activity,family_history,medical_history,cancer_type,cancer_stage
0,29,male,former,light,high,yes,Respiratory Diseases,Mouth,III
1,72,male,former,moderate,low,no,Respiratory Diseases,Brain,IV
2,10,male,current,none,moderate,yes,Stroke,ovarian,II
3,35,male,former,heavy,low,no,Stroke,Lymph,IV
4,6,female,former,none,moderate,no,Thyroid,lung,IV

In [21]:
# Rename columns cleaned_cancer_disease_prediction_df
cleaned_cancer_prediction_df = cleaned_cancer_disease_prediction_df.rename(columns={"age":"Age_at_diagnosis",
                                                                                    "gender":"Gender",
                                                                                    "smoking_status":"Smoking_status",
                                                                                    "alcohol_intake":"Alcohol_intake",
                                                                                    "physical_activity":"Physical_activity",
                                                                                    "family_history":"Family_history",
                                                                                    "medical_history":"Medical_history",
                                                                                    "cancer_type":"Cancer_type",
                                                                                    "cancer_stage":"Cancer_stage"})
cleaned_cancer_prediction_df.head()

,Age_at_diagnosis,Gender,Smoking_status,Alcohol_intake,Physical_activity,Family_history,Medical_history,Cancer_type,Cancer_stage
0,29,male,former,light,high,yes,Respiratory Diseases,Mouth,III
1,72,male,former,moderate,low,no,Respiratory Diseases,Brain,IV
2,10,male,current,none,moderate,yes,Stroke,ovarian,II
3,35,male,former,heavy,low,no,Stroke,Lymph,IV
4,6,female,former,none,moderate,no,Thyroid,lung,IV

In [22]:
cleaned_cancer_prediction_df["Cancer_stage"].unique()

array(['III', 'IV', 'II', 'I'], dtype=object)

In [23]:
# Map TNM Staging to Dukes Staging

# Map TNM Staging to Dukes Staging
cancer_stage_to_dukes_mapping = {
    'I': 'A',
    'II': 'B',
    'III': 'C',
    'IV': 'D',
}
dukes_stage_list = [cancer_stage_to_dukes_mapping[tnm] for tnm in cleaned_cancer_prediction_df['Cancer_stage']]
cleaned_cancer_prediction_df['Dukes_Stage'] = dukes_stage_list
cleaned_cancer_prediction_df.head()

,Age_at_diagnosis,Gender,Smoking_status,Alcohol_intake,Physical_activity,Family_history,Medical_history,Cancer_type,Cancer_stage,Dukes_Stage
0,29,male,former,light,high,yes,Respiratory Diseases,Mouth,III,C
1,72,male,former,moderate,low,no,Respiratory Diseases,Brain,IV,D
2,10,male,current,none,moderate,yes,Stroke,ovarian,II,B
3,35,male,former,heavy,low,no,Stroke,Lymph,IV,D
4,6,female,former,none,moderate,no,Thyroid,lung,IV,D

In [24]:
#save dataframe to a CSV file
cleaned_cancer_prediction_df.to_csv('cleaned_cancer_prediction.csv', index=False)